apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskywebapp
  template:
    metadata:
      labels:
        app: taskywebapp
    spec:
      containers:
      - name: taskywebapp
        image: 070009232298.dkr.ecr.eu-west-1.amazonaws.com/app-repo:taskywebapp_latest
        ports:
        - containerPort: 80
